# Generated by Django 4.2.7 on 2023-12-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
