# Generated by Django 4.2.7 on 2023-12-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
