# Generated by Django 4.2.7 on 2023-12-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_remove_user_cart_quantity_cart_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_quantity',
        ),
    ]
